# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GiphTalk' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GiphTalk

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'GiphTalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GiphTalk-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GiphTalk-tvOS

  target 'GiphTalk-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
